### ISSUE TITLE
accept an array of Connect endpoints instead of one

### ISSUE THREAD

**Issue by andmarios** [Landoop/kafka-connect-ui#21]
Make the `CONNECT_URL` variable to accept an array of URLs instead of just one, in order to support multiple connect clusters.

**Comment by andmarios** [comment]
Implemented with 4e0a884b77d1a8b51377e04a710e22f5a871ab93 .
Available with the latest image from docker hub.

**Comment by Antwnis** [comment]
Closing as fixed per the latest release
