### ISSUE TITLE
Show call name in the "new" view

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-connect-ui#33]
I can find it pretty confusing for example that the Confluent JDBC is called "SQL". 
cf https://fast-data-dev.demo.landoop.com/kafka-connect-ui/#/cluster/fast-data-dev/select-connector

I believe at least the class should appear somewhere. A suggestion:
![image](https://cloud.githubusercontent.com/assets/20851561/25318900/53ae27ea-28da-11e7-8753-59f300870c27.png)

**Comment by Antwnis** [comment]
connector alias has been renamed to JDBC
