### ISSUE TITLE
[bug] key.converter.schemas.enable= not supported

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-connect-ui#36]
`key.converter.schemas.enable=true` should be supported, but it isn't according to the connect ui
(cf https://github.com/apache/kafka/blob/trunk/connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java#L53)

https://media.giphy.com/media/l1KVcbhU9upBOhIpa/giphy.gif

**Comment by andmarios** [comment]
I think this is a global connect setting, not a per connector setting.
Also in order to use it, you should set the JSON converter in the connect configuration.

**Comment by simplesteph** [comment]
You can definitely set it per connector as an override, and that's an expected behaviour. 
As you can see in the gif I also override and set it as JSON Converter. That's definitely acceptable usage

**Comment by andmarios** [comment]
With a bit of input from @jglambed and some testing, I found that when validating the connector, Connect does not return this key (`key.converter.schemas.enable`), so this is why the UI says it is not supported.

I'll let the Connect UI team to think about it. Here are some steps to reproduce the issue with fast-data-dev:

A connector config that does not work in the UI:
```
name=yahoo
connector.class=com.datamountaineer.streamreactor.connect.yahoo.source.YahooSourceConnector
tasks.max=1
connect.yahoo.source.fx.subscriptions=USDGBP=X
connect.yahoo.source.stocks.subscriptions=GOOGL
connect.yahoo.source.fx.topic=yahoo-fx
connect.yahoo.source.stocks.topic=yahoo-stocks
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
```

The same configuration, if we convert to JSON (test.json) and validate against the Connect API:
```
{
    "connector.class": "com.datamountaineer.streamreactor.connect.yahoo.source.YahooSourceConnector",
    "connect.yahoo.source.stocks.subscriptions": "GOOGL",
    "connect.yahoo.source.fx.topic": "yahoo-fx",
    "connect.yahoo.source.stocks.topic": "yahoo-stocks",
    "key.converter.schemas.enable": "true",
    "tasks.max": "1",
    "connect.yahoo.source.fx.subscriptions": "USDGBP=X",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter"
}
```
Validate it with curl:

    curl -X PUT -H "Content-Type: application/json" --data @test.json "http://192.168.99.100:8083/connector-plugins/com.datamountaineer.streamreactor.connect.yahoo.source.YahooSourceConnector/config/validate" | jq .

Notice that the validation does not return errors (so it is valid) but it doesn't include the aforementioned key.

**Comment by simplesteph** [comment]
Thanks for the investigation, I look forward to the fix

**Comment by andmarios** [comment]
Thank you for the report!

@jglambed , @chdask I would dare to say that the whole kafka logic is to just ignore keys that are not recognized. In almost every kafka component, the configuration propagates to all the modules, although only certain parts of it apply to each module. The modules just ignore the keys they don't recognize (and write a line in the log about it).

So instead of failing for an unknown key, I think it is more correct to just issue a warning and let the user create the connector.
