### ISSUE TITLE
UI doesn't connect to the connect rest when building from source

### ISSUE THREAD

**Issue by azimovMichael** [Landoop/kafka-connect-ui#45]
I'm trying to start contributing to the project, and to do so I'm trying to run the ui from the source against 
a kafka-connect that I run as a docker image on my PC.

this is the connect params:
```
  docker run -d   --name=kafka-connect   --net=host 
 -e CONNECT_BOOTSTRAP_SERVERS=localhost:29092  
 -e CONNECT_REST_PORT=28082   -e CONNECT_GROUP_ID="quickstart" 
 -e CONNECT_CONFIG_STORAGE_TOPIC="quickstart-config"
 -e CONNECT_OFFSET_STORAGE_TOPIC="quickstart-offsets" 
 -e CONNECT_STATUS_STORAGE_TOPIC="quickstart-status"  
 -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"   
 -e CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"  
 -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" 
 -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
 -e CONNECT_REST_ADVERTISED_HOST_NAME="localhost" 
 confluentinc/cp-kafka-connect:3.2.1
```

**I have a kafka instance running as a docker image also locally.
When browsing to http://localhost:28082 it shows the version and commit as excepted

this is the env.js file:
```
//Change the URLs of the endpoints here
var clusters = [
   {
     NAME:"prod",
     KAFKA_CONNECT: "http://localhost:28082",
     COLOR: "#141414"
   },
   {
     NAME:"dev1",
     KAFKA_CONNECT: "http://kafka-connect.dev.url",
     KAFKA_TOPICS_UI_ENABLED: false
   }
]
```
then I start the server with http-server .
but it still shows the cluster as not responding.

Of course, that I want only the first cluster to be available.

**Comment by andmarios** [comment]
I suspect CORS issues as the Connect API and the Connect UI are served from a different ports.
Can you check your browser's logs (developers console for chrome, etc) for any error?

**Comment by azimovMichael** [comment]
Yes, it says` XMLHttpRequest cannot load http://localhost:28082/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`
Tried adding the `ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*" -e ACCESS_CONTROL_ALLOW_METHODS_DEFAULT=GET,POST,PUT,DELETE,OPTIONS -e ACCESS_CONTROL_ALLOW_ORIGIN=* -e ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS`
to the connect api but didnt help

**Comment by andmarios** [comment]
Connect does not support these options yet. Schema Registry and Kafka REST do.

Our devs usually use caddy for local development. It is a very simple web server that allows easy proxying. So it both serves the Connect UI and proxies the Connect API, so that both are served from the same port.

https://caddyserver.com/

And a sample configuration for caddy (change the port and the root to your dev directory):
```
0.0.0.0:8000
tls off
root /path/to/connect-ui/source
proxy /api/connect http://localhost:28082 {
    without /api/connect
}
```

For Connect UI (env.js):
```
var clusters = [
   {
     NAME:"prod",
     KAFKA_CONNECT: "/api/connect",
     COLOR: "#141414"
   }
]
```

**Comment by azimovMichael** [comment]
Will try and update ASAP. Thnx.

**Comment by azimovMichael** [comment]
IT WORKS. Thank you.

**Comment by andmarios** [comment]
Cool! Glad I could help!
