### ISSUE TITLE
Error when start kafka-connect-ui container: Interrupted system call 

### ISSUE THREAD

**Issue by bwalsh** [Landoop/kafka-connect-ui#47]
Seems very similar to : https://github.com/Landoop/kafka-topics-ui/issues/77

My env:

docker --version
Docker version 17.09.0-ce, build afdb6d4

Ubuntu 16.04 LTS 

Openstack

**Comment by andmarios** [comment]
Hey @bwalsh, sorry for the very late response, somehow I've missed your issue. I did implement the fix 14 days ago though, at bed3bbcc33b63e6c84a17c44a2f83ebeadc87bf3 and updated the image in docker hub (the build is automated on github push, so it is already up for 14 days). Could you test with the latest image?

**Comment by Antwnis** [comment]
I'm resolving this issue, as a fix has been put in place - that has been tested on other dockers as well

Feel free to re-open if this persists
