### ISSUE TITLE
Connect topology shows wrong topics

### ISSUE THREAD

**Issue by kanimaru** [Landoop/kafka-connect-ui#53]
Using:  
- Kafka Connect Version : 0.11.0.0-cp1
- Kafka Connect UI Version : 0.9.2 
- ElasticSearch (confluent) Worker

Configuration like this:
```
{
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "type.name": "action",
  "flush.timeout.ms": "10000",
  "topics": "action-log",
  "tasks.max": "1",
  "batch.size": "1000",
  "topic.key.ignore": "true",
  "topic.index.map": "action-log:log",
  "name": "my_logger",
  "connection.url": "http://somedomain:9200",
  "linger.ms": "10",
  "topic.schema.ignore": "false"
}
```

Following Topics will be recognized:
- action-log
- true
- action-log:log
- false

**Comment by stheppi** [comment]
@kanimaru 
  We are accepting PRs. Feel free to provide one.

**Comment by andmarios** [comment]
Hey @kanimaru, the problem is that the `topics` field isn't standard in Kafka Connect, so we can't rely on it in order to detect the topics your connector uses.

Thus, trying to be smart, we will use any configuration option that includes `topic` in its name in order to detect topics. Alas in your case it backfires and Connect UI detect erroneous topic names.

I don't know whether there are any plans to fix this in the short term.

**Comment by namoscato** [comment]
@andmarios, that is true for source connectors, but per [Kafka documentation](https://kafka.apache.org/documentation/#connect_configuring), sink connectors will always have a `topics` option. Thus, I believe an explicit assumption could be made for sinks.

Here are the topic-related configuration option(s) for some common source connectors:

| Connector | Option |
|---|---|
|`JdbcSourceConnector `|[`topic.prefix`](https://docs.confluent.io/current/connect/connect-jdbc/docs/source_config_options.html#connector)|
|`ReplicatorSourceConnector`|[`topic.regex`, `topic.whitelist`, `topic.blacklist`](https://docs.confluent.io/current/connect/connect-replicator/docs/configuration_options.html#source-topics)
|`FileStreamSource`|[`topic`](https://docs.confluent.io/current/connect/connect-filestream/filestream_connector.html#filesource-connector)|
|`SpoolDirCsvSourceConnector`|[`topic`](https://github.com/jcustenborder/kafka-connect-spooldir#spooldircsvsourceconnector)
|`FsSourceConnector `|[`topic`](http://kafka-connect-fs.readthedocs.io/en/latest/config_options.html#general)
|`FtpSourceConnector `|[`ftp.monitor.tail`, `ftp.monitor.update`](https://github.com/Eneco/kafka-connect-ftp#properties)
|`GitHubSourceConnector `|[`topic`](https://github.com/simplesteph/kafka-connect-github-source#configuration)|
|`CloudPubSubSourceConnector `|[`kafka.topic`](https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector#source-connector)
|`IotHubSourceConnector`|[`Kafka.Topic`](https://github.com/Azure/toketi-kafka-connect-iothub/blob/master/README_Source.md#configuration)|
|`CouchbaseSourceConnector`|[`topic.name`](https://github.com/couchbase/kafka-connect-couchbase/blob/master/config/quickstart-couchbase-source.properties)
|`ReplicateSourceConnector`|[`topic.prefix`](http://replicate-connector-for-kafka.readthedocs.io/en/latest/source_config_options.html#all-user-configuration-properties)
|`KineticaSourceConnector`|[`kinetica.topic_prefix`](https://github.com/kineticadb/kinetica-connector-kafka#streaming-data-from-kinetica-into-kafka)
|`HANASourceConnector`|[`topics`](https://github.com/SAP/kafka-connect-sap#configuration)

Clearly some of these are more complex than others (i.e. connectors with configuration options similar to `ReplicatorSourceConnector`), but thoughts on updating the source connector "topic extraction" algorithm to first try and find a single configuration option that matches the following regular expression?

```regex
/(?:kafka[._])?topics?(?:[._]prefix)?$/
```

It seems like that would fix most of the issues.

**Comment by andmarios** [comment]
Thanks! This is very helpful indeed.

I tagged some members of the UIs dev team to have a look and implement it when possible.
