### ISSUE TITLE
Source plugin and its connectors showing as sink

### ISSUE THREAD

**Issue by jimhub** [Landoop/kafka-connect-ui#54]
**kafka-connect-ui version:** 0.9.3
**kafka-connect version:** 1.0.0

I am using a mysql connect plugin (io.debezium.connector.mysql.MySqlConnector) which registers as the 'source' type in connect, as shown in the output of `/connector-plugins`:

```
[
  {
    "class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "type": "sink",
    "version": "3.2.0"
  },
  {
    "class": "io.debezium.connector.mysql.MySqlConnector",
    "type": "source",
    "version": "0.7.0"
  },
  {
    "class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
    "type": "sink",
    "version": "1.0.0"
  },
  {
    "class": "org.apache.kafka.connect.file.FileStreamSourceConnector",
    "type": "source",
    "version": "1.0.0"
  }
]
```

However, in the UI it is displaying as a 'sink' plugin, and its connectors displaying as 'sink' connectors:

![screen shot 2018-01-05 at 12 09 31 pm](https://user-images.githubusercontent.com/5760517/34624160-7c0865ba-f211-11e7-8ff3-08584311deed.png)

![screen shot 2018-01-05 at 12 10 00 pm](https://user-images.githubusercontent.com/5760517/34624165-805bf4b0-f211-11e7-8bbf-90bcf1d308d5.png)

This is also despite the stored 'type' of the connector(s) being 'source':

```
{
  "name": "sensors",
  "config": {
    ...
  },
  "tasks": [
    {
      "connector": "sensors",
      "task": 0
    }
  ],
  "type": "source"
}
```

Not a huge issue, but I thought I'd pass it along. Let me know if you need more info. Thanks!

**Comment by jglambed** [comment]
Hi @jimhub 
If the connector plugin is not included in our "supported" plugins we try to identify it as Sink or Source by reading its classname - Kafka Connect was not giving away the type of the plugin until version 1.0.0.

Unfortunately, "io.debezium.connector.mysql.MySqlConnector" is not very informative and Kafka Connect UI classifies it as "Sink". 

Thank you for mentioning it, we have to take a closer look into this and align it with the newer versions of Kafka Connect.

**Comment by jglambed** [comment]
Hi @jimhub, this must be fine now.
Feel free to check it yourself and tell us if something is wrong.

**Comment by lwu08** [comment]
I got the same issue with my source connector. Its name is "com.dct.kafka.connect.source.OPSourceConnector", which includes "source", but still recognized as sink by connector UI.  So what should be the correct naming for it? Thanks.

**Comment by Antwnis** [comment]
@lwu08 you will need to edit https://github.com/Landoop/kafka-connect-ui/blob/master/src/supported-connectors.js and add an entry for your connector

**Comment by lwu08** [comment]
@Antwnis Thanks for pointing this out. 
If I am using docker, I guess I need to build the image by myself to make updates in supported-connectors.js works, right? Any way to void this?

**Comment by gotojeffray** [comment]
Hi there, I got the same problem : my sql server connector showing as sink
Kafka Connect : /api/kafka-connect-1 
Kafka Connect Version : 2.2.0-cp2 
Kafka Connect UI Version : 0.9.4

**Comment by Hubbitus** [comment]
For `io.debezium.connector.sqlserver.SqlServerConnector` I still see in version `0.9.7 ` it is marked as `sink` connector.

**Comment by morozov** [comment]
I can confirm the above. `io.debezium.connector.mysql.MySqlConnector`s are displayed as a sink in Kafka Connect UI 0.9.7.
