### ISSUE TITLE
Support editable JSON on connector creation

### ISSUE THREAD

**Issue by namoscato** [Landoop/kafka-connect-ui#58]
Currently, a properties-based format is converted to JSON on connector creation. The lack of JSON support is also inconsistent with the edit functionality, which uses JSON.

**Comment by stheppi** [comment]
Can you please describe in tech details the requirements? Otherwise your issue seems like a complain 😊

Also Pull requests are welcome!

**Comment by namoscato** [comment]
Yeah, I was just creating this as a placeholder actually; I should be able to grab it this weekend.

I'm not entirely sure how else to describe the feature request. Said differently, I really think the connector creation UI should support and/or default to a JSON format as opposed to a properties-based format. In this world, all interactions with connector creation / edit would deal with JSON, matching the REST API request body content type directly.

**Comment by stheppi** [comment]
Why would editing a json , which is not necessarily straightforward considering the payload required by connect, be better than property based? What is the benefit?  Is less readable than property based, then depending on the connector could make it harder to identify key information.

**Comment by namoscato** [comment]
It's just inconsistent from my perspective.

Specifically as it relates to this project, editing connector configurations deals solely with JSON, not properties. With that said, supporting a properties-based format in this edit UI would be another way to mitigate the inconsistency.

As it relates to my personal usage, I would prefer to only interact with JSON such that it matches the REST API request body content type across the board. In my case, I am using this project locally but not in other environments where I interact with the REST API directly; thus, it would be ideal to use JSON across the board.

With all of that said, would you guys be opposed to at least adding support for editable JSON on connector creation before I go down that path?

**Comment by Antwnis** [comment]
Hi @namoscato 

There are 2 schools of thought classing a bit here :-)

One is pushing for JSon ( as this is what i use on the REST API )
One is pushing for property based ( as this is how i configure my kubernetes/helm/standalone )

I agree that (i) consistency makes a lot of sense: On the UI show either property/or/json 

The best user-experience, would be to (a) standardize on one of them and (b) introduce a small button to switch the content property <-> json , so both schools of thought are happy 

WDYT ?

**Comment by namoscato** [comment]
Yeah, I'm all for supporting both.

Let's default to properties and add the ability to toggle to JSON?

I should be able to take at pass at things within the week, but feel free to drop some UI ideas / additional thoughts for me to incorporate.

**Comment by Antwnis** [comment]
I agree on defaulting to (properties) - and allow toggling to JSon 

I think @simplesteph had raised this on #41 - so looking forward to your PR !!
