### ISSUE TITLE
Wrong topic names when using topics.dir 

### ISSUE THREAD

**Issue by maver1ck** [Landoop/kafka-connect-ui#66]
Connect UI is reading topic name from topics.dir options.
This options only show path on filesystem. Not the topic names that connector is using.

**Comment by jglambed** [comment]
Hi @maver1ck ,
Can you please tell us witch version of kafka-connect-ui are you using? @namoscato did a great job on fixing this issue, but it is not yet released. You can have it though by building kafka-connect-ui from source.

**Comment by maver1ck** [comment]
I was using 0.9.3.
In which version you will provide changes ?

**Comment by jglambed** [comment]
We are planning to include this changes in the next release, in 0.9.5 version.

**Comment by cricket007** [comment]
Want to clarify since I think this is what I see as well - running 0.9.4. The `topics.dir` is being interpreted as a topic name. 

It makes the [Sankey Diagram](https://bost.ocks.org/mike/sankey/) thing on the UI look rather weird too.

**Comment by namoscato** [comment]
Yeah, previously the algorithm would match any configuration option that contained `topic`.

This was improved in #62 which:

* strictly uses the `topics` option for **sink connectors**
* first checks **source connector** options against a [tighter regular expression](https://github.com/Landoop/kafka-connect-ui/pull/62/files#diff-4943ad574419a4c238107c5d48a39bffR4) before falling back on the previous algorithm

This should fix most scenarios. Checkout https://github.com/Landoop/kafka-connect-ui/issues/53#issuecomment-362845591 for some more context.
