### ISSUE TITLE
Restarting a failed task

### ISSUE THREAD

**Issue by samanta1983** [Landoop/kafka-connect-ui#67]
The restart button in the UI attempts to restart the connector.

 "POST /connectors/ES-sink/restart HTTP/1.1" 204 -  18 (org.apache.kafka.connect.runtime.rest.RestServer:60)

Is it possible to restart individual task from the UI?

/connectors/ES-sink/restart/tasks/0/restart

**Comment by jglambed** [comment]
Hi @samanta1983,
Restarting a task from kafka-connect-ui is a functionality that we are planning to add in the near future. Unfortunately I cannot give you an ETA right now.

**Comment by asdf2014** [comment]
Hi @samanta1983 @jglambed . It seems that already existed RESTful api to suport the new feature. `$ curl -X POST localhost:8083/connectors/file-sink/tasks/0/restart | jq`.

**Comment by asdf2014** [comment]
![image](https://user-images.githubusercontent.com/8108788/37326661-238891ca-26ce-11e8-8a13-094878885a70.png)

**Comment by asdf2014** [comment]
@samanta1983 @jglambed Already add the new feature in #72 . PTAL.

**Comment by Tapppi** [comment]
@jglambed @asdf2014 Could you release a new version with the restart task button? Would help immenseley with a very unstable connector we are running..

**Comment by andmarios** [comment]
Hi @lixiandai. This feature is on docker hub since July.
You can get it either by pulling the `latest` tag, or one of `0.9.5` and `0.9.6`.

If you can't see the button, try to hard-refresh your browser. For Chrome you would bring up the developer console, then press F5.
