### ISSUE TITLE
Cannot decrease the number of task of connector after created a connector that owns lots of tasks, even if delete it

### ISSUE THREAD

**Issue by asdf2014** [Landoop/kafka-connect-ui#71]
Cannot decrease the number of task of connector after created a connector that owns lots of tasks, even if delete it...

Created a connector with 6 tasks.
![image](https://user-images.githubusercontent.com/8108788/37331353-a9eb7646-26de-11e8-882b-cfa3e4756020.png)

Delete it
![image](https://user-images.githubusercontent.com/8108788/37331379-b9be078c-26de-11e8-842f-d6ca0d9ce3d2.png)

Wanna create a connector with 1 task.
![image](https://user-images.githubusercontent.com/8108788/37331421-de0af3c0-26de-11e8-8851-d622deb2a68c.png)

Still have 6 tasks...
![image](https://user-images.githubusercontent.com/8108788/37331461-fbf33370-26de-11e8-9bee-b8c787f7bb24.png)

**Comment by jglambed** [comment]
Kafka connect takes some time to apply the changes, and we do not (and cannot) get them real time with this UI tool. If you tried to refresh the page after a minute or so it should display the correct number of tasks. 
Can you please confirm?

**Comment by asdf2014** [comment]
Hi, @jglambed . Okay, i will confirm it tomorrow…

**Comment by asdf2014** [comment]
@jglambed Sorry, too busy recently. I confirmed the number of tasks will show the correct number after a while.
