### ISSUE TITLE
Unable to enter a equal sign into property value.

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [Landoop/kafka-connect-ui#83]
I would like to enter the following property:

`key=set value=1`

There is currently no way to include an equal sign using the property syntax due to the logic at: https://github.com/Landoop/kafka-connect-ui/blob/master/src/kafka-connect/configuration/editor/configuration-editor-properties.component.js#L72-L76

Could you please add this ability? I don't care what the syntax looks like, I just need the ability to enter an equal sign into the value :)

Thanks for your time!

**Comment by andmarios** [comment]
Nice catch @thomasdziedzic-pd! I'll pass it to the team.

Until fixed, as a workaround, you can use the UI to set / validate your connector settings, then switch to the `curl` tab, copy the command, fix the field with the equal sign and run it in the command line.

**Comment by ulfox** [comment]
Hello @thomasdziedzic-pd , release 0.9.7 is now available.

You can now use the latest or 0.9.7 version!

Regards,
