### ISSUE TITLE
"flush.size" : Invalid value for configuration flush.size: Not a number of type INT

### ISSUE THREAD

**Issue by rupeshmore85** [Landoop/kafka-connect-ui#84]
I downloaded latest version of Landoop-ui (v0.9.6) to submit hdfs sink connector configurations running on confluent 5.0.0. 
The Create button is not activated due to below error :

Landoop UI complains about Invalid syntax even though i have provided the flush.size and it is an INT. This configurations work with v0.9.4

![image](https://user-images.githubusercontent.com/2333080/45563636-f347d900-b81b-11e8-8705-46a624c2bef3.png)

**Comment by andmarios** [comment]
Hi @rupeshmore85. This seems funny!

I tried to reproduce it with `landoop/fast-data-dev:2.0` (which has Kafka 2.0 and HDFS connector 5.0) but couldn't. Could you do try to remove the problematic entry and re-type it by hand?
The error comes from the connect worker itself, the UI just shows it.

**Comment by rupeshmore85** [comment]
Thanks @andmarios for the reply. Yeah when i copy paste the connector config settings, it complains about the flush.size, but when i tried taking one by one parameters out of the config, found that : path.format='filedate'=YYYY-MM-dd/ is the one having issue.

![image](https://user-images.githubusercontent.com/2333080/45589180-65d5b900-b8ef-11e8-9820-88ae4ee1f459.png)

When i take the path.format out, the connector is valid:

![image](https://user-images.githubusercontent.com/2333080/45589186-8ef64980-b8ef-11e8-8143-2a07a744fe59.png)

I think, the equal sign in 'filedate'=YYYY-MM-dd/ is causing the problem, how do i escape the equal sign.

**Comment by andmarios** [comment]
Ah, this is a known shortcoming of Kafka Connect UI. Unfortunately, I can't provide a date for when the fix will be available.

Please track the open issue about this bug here: https://github.com/Landoop/kafka-connect-ui/issues/83
